version: '3.1'

services:

  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    restart: always
    environment:
      SA_PASSWORD: "Ex@mple12345678"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - 1433:1433

  #mysql:
  #  image: mysql
  #  command: --default-authentication-plugin=mysql_native_password
  #  restart: always
  #  ports:
  #    - 3306:3306
  #  environment:
  #    MYSQL_ROOT_PASSWORD: example

  #postgres:
  #  image: postgres
  #  restart: always
  #  ports:
  #    - 5432:5432
  #  environment:
  #    POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

  dbbro:
    build:
      context: .
    ports:
      - 8082:8080
    volumes:
      - ./config.json:/dbbro/src/server/config.json
